<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260308170859 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial migration to create products and price_history_entries tables with necessary constraints and indexes.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE products (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            sku VARCHAR(64) NOT NULL,
            price NUMERIC(10, 2) NOT NULL,
            currency VARCHAR(3) NOT NULL,
            status VARCHAR(16) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            version INT DEFAULT 1 NOT NULL, PRIMARY KEY (id))'
        );

        $this->addSql('CREATE TABLE price_history_entries (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            old_price NUMERIC(10, 2) NOT NULL,
            new_price NUMERIC(10, 2) NOT NULL,
            changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            product_id INT NOT NULL,
            PRIMARY KEY (id))'
        );

        $this->addSql('
            CREATE INDEX idx_price_history_product
            ON price_history_entries (product_id)'
        );

        $this->addSql('
            CREATE UNIQUE INDEX uniq_active_product_sku
            ON products (sku)
            WHERE deleted_at IS NULL'
        );

        $this->addSql('
            ALTER TABLE price_history_entries
            ADD CONSTRAINT FK_CBF3083D4584665A
            FOREIGN KEY (product_id) REFERENCES products (id)
            ON DELETE CASCADE NOT DEFERRABLE'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE price_history_entries DROP CONSTRAINT FK_CBF3083D4584665A');
        $this->addSql('DROP INDEX uniq_active_product_sku');
        $this->addSql('DROP INDEX idx_price_history_product');
        $this->addSql('DROP TABLE price_history_entries');
        $this->addSql('DROP TABLE products');
    }
}
